# Compare Numpy with List

In [1]:
import numpy as np

In [9]:
my_array = np.arange(1000000)

In [10]:
my_list = list(range(1000000))

In [11]:
%time for _ in range(50): my_array * 2

Wall time: 507 ms


In [12]:
%time for _ in range(50): my_list * 2

Wall time: 6.31 s


# 4.1 The NumPy ndarray: A Multidimensional Array Object

In [3]:
#(rows, columns)
x = np.random.randn(2, 3)

In [4]:
#(rows, columns)
y = np.random.randn(8, 4)

In [21]:
x

array([[-0.01520741, -0.72837525,  0.07076799],
       [ 1.22969933,  0.35499111,  1.75699921]])

In [24]:
y

array([[-0.66651003,  0.75702736, -1.9576011 ,  1.5177726 ],
       [-0.51813929,  0.48214802, -0.69291341, -0.64544476],
       [ 0.90144642,  1.47986954,  1.09900056,  1.37211157],
       [-0.50139148, -0.62882343,  0.73659693, -0.65730852],
       [ 0.2172839 ,  0.28325931,  0.2053734 , -0.79836251],
       [ 0.01639927, -1.66315687,  0.27690046,  1.98745712],
       [ 1.66024351,  0.64330548,  0.29474162, -0.21863125],
       [-0.4483943 , -1.08071825,  1.21844428,  1.18707052]])

In [26]:
x * 10

array([[-0.15207407, -7.28375246,  0.70767989],
       [12.29699333,  3.54991112, 17.56999213]])

In [27]:
y * 10

array([[ -6.66510027,   7.57027356, -19.57601102,  15.17772597],
       [ -5.18139288,   4.8214802 ,  -6.92913406,  -6.45444756],
       [  9.01446419,  14.79869536,  10.99000559,  13.72111568],
       [ -5.01391477,  -6.28823426,   7.36596926,  -6.57308523],
       [  2.17283897,   2.83259307,   2.05373401,  -7.98362505],
       [  0.16399267, -16.63156872,   2.76900457,  19.87457122],
       [ 16.6024351 ,   6.43305483,   2.94741623,  -2.18631251],
       [ -4.48394304, -10.80718255,  12.18444285,  11.87070515]])

In [5]:
x.dtype

dtype('float64')

In [6]:
x.shape

(2, 3)

# Creating ndarray

In [8]:
xarr = np.array([[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]])

In [9]:
xarr.dtype

dtype('int32')

In [10]:
xarr.ndim

2

In [11]:
xarrr = np.array([[[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]]])

In [12]:
xarrr.ndim

3

In [13]:
xarrr

array([[[ 1,  2,  3,  4,  5],
        [11, 22, 33, 44, 55]]])

In [14]:
xarr.shape

(2, 5)

In [15]:
xarrr.shape

(1, 2, 5)

In [29]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.empty((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.zeros((1, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [26]:
np.zeros((2, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [28]:
np.zeros((3, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [33]:
list1 = [1, 2, 3, 4, 5]
np.asarray(list1)

array([1, 2, 3, 4, 5])

In [11]:
abc1 = np.array([1, 2, 3])

In [12]:
abc1.dtype

dtype('int32')

In [13]:
abc2 = abc1.astype(np.float64)

In [14]:
abc1.dtype

dtype('int32')

In [17]:
abc2.dtype

dtype('float64')

In [34]:
list1

[1, 2, 3, 4, 5]

In [35]:
np.array(list1)

array([1, 2, 3, 4, 5])

In [36]:
list1

[1, 2, 3, 4, 5]

In [41]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [49]:
mn = np.ones((2, 3), dtype="float32")
mn

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [48]:
np.ones_like(mn, dtype="int64")

array([[1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [50]:
## alternate zeros() and zeros_like()

In [4]:
x = np.empty((2, 3))
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
gf = np.empty_like(x)
gf

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
c = np.full((2, 3), fill_value='3', dtype="int32")
c

array([[3, 3, 3],
       [3, 3, 3]])

In [19]:
np.full_like(c, fill_value=23)

array([[23, 23, 23],
       [23, 23, 23]])

In [26]:
np.eye(5, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Data Types for ndarrays



In [34]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [35]:
arr1.dtype

dtype('float64')

In [36]:
arr2.dtype

dtype('int32')

In [37]:
# float32 is float
# int32 is integer
# float64 is Double

### Numpy more Data Types

In [41]:
int8_array1 = np.array([1, 2, 3], dtype=np.int8)
int8_array2 = np.array([1, 2, 3], dtype=np.uint8)
print(int8_array1.dtype)
int8_array2.dtype

int8


dtype('uint8')

In [43]:
int16_a = np.array([1, 2, 3], dtype=np.int16)
int32_a = np.array([1, 2, 3], dtype=np.int32)
int64_a = np.array([1, 2, 3], dtype=np.int64)

In [46]:
float16_a = np.array([1, 2, 3], dtype=np.float16)
float32_a = np.array([1, 2, 3], dtype=np.float32)
float64_a = np.array([1, 2, 3], dtype=np.float64)
#float128_a = np.array([1, 2, 3], dtype=np.float128)

In [2]:
c64 = np.array([1, 2, 3], dtype=np.complex64)

In [3]:
c64

array([1.+0.j, 2.+0.j, 3.+0.j], dtype=complex64)

In [4]:
c64 = np.array([[1, 2, 3], [11, 22, 33]], dtype=np.complex64)

In [5]:
c64

array([[ 1.+0.j,  2.+0.j,  3.+0.j],
       [11.+0.j, 22.+0.j, 33.+0.j]], dtype=complex64)

In [6]:
# complex128 and complex256

In [7]:
bol = np.array([1, 2, 3], dtype=np.bool)

In [8]:
bol

array([ True,  True,  True])

In [9]:
list1 = list([1, 2, 3])
list2 = list([4, 5, 6])
obj = np.array([list1, list2], dtype=np.object)

In [10]:
obj

array([[1, 2, 3],
       [4, 5, 6]], dtype=object)

In [31]:
str1 = np.array([1.2, 3.3, 6.6, 1.0, 3.4, 1.2], dtype=np.string_)

In [32]:
str1

array([b'1.2', b'3.3', b'6.6', b'1.0', b'3.4', b'1.2'], dtype='|S3')

In [25]:
str1.astype(np.float32)

array([1.2, 3.3, 6.6, 1. , 3.4], dtype=float32)

In [27]:
str2 = np.array(['aa','b', 'cd', 'd', 'efg', 'shk', 'ijkl'], dtype=np.string_)

In [28]:
str2

array([b'aa', b'b', b'cd', b'd', b'efg', b'shk', b'ijkl'], dtype='|S4')

In [33]:
uni1 = np.array([1.2, 3.4, 0.1, 45.9], dtype=np.unicode_)

In [34]:
uni1

array(['1.2', '3.4', '0.1', '45.9'], dtype='<U4')

In [35]:
uni2 = np.array(['abc', 'shk', 'ger', 'arg', 'shakeel'], dtype=np.unicode_)

In [36]:
uni2

array(['abc', 'shk', 'ger', 'arg', 'shakeel'], dtype='<U7')