In [1]:
import numpy as np

# Arithmetic with NumPy Arrays

In [6]:
x = 2*2
x1 = 2**2

In [8]:
print(type(x))
print(type(x1))

<class 'int'>
<class 'int'>


In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [10]:
arr.dtype

dtype('int32')

In [11]:
arr.ndim

2

In [12]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr + arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [4]:
arr ** arr

array([[    1,     4,    27],
       [  256,  3125, 46656]], dtype=int32)

In [15]:
arr / arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [5]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [4]:
arr == arr

array([[ True,  True,  True],
       [ True,  True,  True]])

In [5]:
arr < arr

array([[False, False, False],
       [False, False, False]])

In [6]:
arr != arr

array([[False, False, False],
       [False, False, False]])

In [7]:
arr > arr

array([[False, False, False],
       [False, False, False]])

In [9]:
arr in arr

True

In [10]:
12 in arr

False

In [12]:
4 in arr

True

# Basic Indexing and Slicing

In [13]:
abr = np.arange(20)

In [14]:
abr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
abr[5]

5

In [16]:
abr[5:8]

array([5, 6, 7])

In [17]:
abr_slice = abr[5:9]

In [18]:
abr_slice

array([5, 6, 7, 8])

In [19]:
abr_slice[0:2] = 12

In [20]:
abr_slice

array([12, 12,  7,  8])

In [21]:
abr_slice

array([12, 12,  7,  8])

In [22]:
abr

array([ 0,  1,  2,  3,  4, 12, 12,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
a1 = abr[2:9]

In [24]:
a2 = abr[0:5]

In [25]:
a1[0] = 123

In [26]:
a1

array([123,   3,   4,  12,  12,   7,   8])

In [27]:
abr

array([  0,   1, 123,   3,   4,  12,  12,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [28]:
a3 = np.array(abr[7:12])

In [29]:
a3

array([ 7,  8,  9, 10, 11])

In [30]:
a3[1] = 888

In [31]:
a3

array([  7, 888,   9,  10,  11])

In [32]:
abr

array([  0,   1, 123,   3,   4,  12,  12,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [33]:
a2

array([  0,   1, 123,   3,   4])

In [36]:
a4 = abr[1:10].copy()

In [37]:
a4

array([  1, 123,   3,   4,  12,  12,   7,   8,   9])

In [38]:
a4[1] = 4545

In [39]:
a4

array([   1, 4545,    3,    4,   12,   12,    7,    8,    9])

In [40]:
abr

array([  0,   1, 123,   3,   4,  12,  12,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [49]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [50]:
arr3d.ndim

3

In [51]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [53]:
arr3d[:]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [54]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [56]:
arr3d[0][0]

array([1, 2, 3])

In [57]:
arr3d[1][0]

array([7, 8, 9])

In [58]:
x = arr3d[0].copy()

In [59]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
x.ndim

2

In [65]:
x[1, 1:]

array([5, 6])

# Boolean Indexing

In [8]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [9]:
data = np.random.randn(7, 4)

In [10]:
data

array([[ 1.7184027 , -0.39647948, -0.53869207, -1.55854932],
       [-0.62338804,  0.63237499,  0.72816678, -1.07302269],
       [ 2.24572984,  0.27159929,  0.41334822,  1.88841633],
       [ 0.94124538,  0.14680533, -0.48138741, -0.49206847],
       [ 1.95813404,  1.62970225, -1.06609272, -0.0746713 ],
       [ 0.12834681,  0.93184297, -1.19407468,  1.00311817],
       [-0.03957284, -0.06126156,  0.37745763,  0.11411531]])

In [11]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [12]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [14]:
data[names=='Bob']

array([[ 1.7184027 , -0.39647948, -0.53869207, -1.55854932],
       [ 0.94124538,  0.14680533, -0.48138741, -0.49206847]])

In [15]:
data[names == 'Bob', 2:]

array([[-0.53869207, -1.55854932],
       [-0.48138741, -0.49206847]])

In [18]:
data[names == 'Will', 2]

array([ 0.41334822, -1.06609272])

In [19]:
data[names != 'Bob']

array([[-0.62338804,  0.63237499,  0.72816678, -1.07302269],
       [ 2.24572984,  0.27159929,  0.41334822,  1.88841633],
       [ 1.95813404,  1.62970225, -1.06609272, -0.0746713 ],
       [ 0.12834681,  0.93184297, -1.19407468,  1.00311817],
       [-0.03957284, -0.06126156,  0.37745763,  0.11411531]])

In [21]:
data[~(names == 'Bob')]

array([[-0.62338804,  0.63237499,  0.72816678, -1.07302269],
       [ 2.24572984,  0.27159929,  0.41334822,  1.88841633],
       [ 1.95813404,  1.62970225, -1.06609272, -0.0746713 ],
       [ 0.12834681,  0.93184297, -1.19407468,  1.00311817],
       [-0.03957284, -0.06126156,  0.37745763,  0.11411531]])

In [22]:
cond = names == 'Bob'

In [23]:
cond

array([ True, False, False,  True, False, False, False])

In [24]:
data[~cond]

array([[-0.62338804,  0.63237499,  0.72816678, -1.07302269],
       [ 2.24572984,  0.27159929,  0.41334822,  1.88841633],
       [ 1.95813404,  1.62970225, -1.06609272, -0.0746713 ],
       [ 0.12834681,  0.93184297, -1.19407468,  1.00311817],
       [-0.03957284, -0.06126156,  0.37745763,  0.11411531]])

In [25]:
mask = (names == 'Bob') | (names == 'Will')

In [26]:
mask

array([ True, False,  True,  True,  True, False, False])

In [27]:
data[mask]

array([[ 1.7184027 , -0.39647948, -0.53869207, -1.55854932],
       [ 2.24572984,  0.27159929,  0.41334822,  1.88841633],
       [ 0.94124538,  0.14680533, -0.48138741, -0.49206847],
       [ 1.95813404,  1.62970225, -1.06609272, -0.0746713 ]])

In [28]:
data[data < 0] = 0

In [29]:
data

array([[1.7184027 , 0.        , 0.        , 0.        ],
       [0.        , 0.63237499, 0.72816678, 0.        ],
       [2.24572984, 0.27159929, 0.41334822, 1.88841633],
       [0.94124538, 0.14680533, 0.        , 0.        ],
       [1.95813404, 1.62970225, 0.        , 0.        ],
       [0.12834681, 0.93184297, 0.        , 1.00311817],
       [0.        , 0.        , 0.37745763, 0.11411531]])

In [30]:
data[names == 'Joe'] = 7

In [31]:
data

array([[1.7184027 , 0.        , 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [2.24572984, 0.27159929, 0.41334822, 1.88841633],
       [0.94124538, 0.14680533, 0.        , 0.        ],
       [1.95813404, 1.62970225, 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ]])

# Fancy Indexing

In [33]:
arr = np.empty((8, 4))

In [34]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
for i in range(8):
    arr[i] = i

In [36]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [37]:
arr[[1, 2, 3]]

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [38]:
arr = np.arange(32).reshape((8, 4))

In [39]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [41]:
arr[[1, 2, 3], [0, 1, 2]] # (1, 0) (2, 1) (3, 2)

array([ 4,  9, 14])

# Transposing Arrays and Swapping Axes

In [42]:
art = np.arange(15).reshape((3, 5))

In [43]:
art

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
art.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [45]:
np.dot(art, art.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [46]:
art = np.arange(24).reshape((4, 6))

In [47]:
art

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [48]:
art.T

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

In [49]:
art.shape

(4, 6)

In [50]:
art

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [51]:
cc = art.T

In [52]:
cc

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

In [53]:
cc.shape

(6, 4)

In [54]:
ary = np.arange(24).reshape((3, 2, 4))

In [55]:
ary

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [56]:
cc = ary.T

In [57]:
cc

array([[[ 0,  8, 16],
        [ 4, 12, 20]],

       [[ 1,  9, 17],
        [ 5, 13, 21]],

       [[ 2, 10, 18],
        [ 6, 14, 22]],

       [[ 3, 11, 19],
        [ 7, 15, 23]]])

In [58]:
cc.shape

(4, 2, 3)

In [59]:
aru = np.arange(20).reshape((2, 2, 5))

In [60]:
aru

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [61]:
## to learn transpose and swapaxes

In [2]:
arr = np.arange(15).reshape((5, 3))

In [5]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [6]:
arr.transpose()

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [7]:
arr.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [8]:
art = np.arange(20).reshape((2, 2, 5))

In [9]:
art

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [10]:
art.transpose()

array([[[ 0, 10],
        [ 5, 15]],

       [[ 1, 11],
        [ 6, 16]],

       [[ 2, 12],
        [ 7, 17]],

       [[ 3, 13],
        [ 8, 18]],

       [[ 4, 14],
        [ 9, 19]]])

In [11]:
art.T

array([[[ 0, 10],
        [ 5, 15]],

       [[ 1, 11],
        [ 6, 16]],

       [[ 2, 12],
        [ 7, 17]],

       [[ 3, 13],
        [ 8, 18]],

       [[ 4, 14],
        [ 9, 19]]])

In [12]:
art.ndim

3

In [13]:
art

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [14]:
art.shape

(2, 2, 5)

In [15]:
art.transpose().shape

(5, 2, 2)

In [16]:
art.T.shape

(5, 2, 2)

In [17]:
art

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [18]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [25]:
arr.swapaxes(1, 0)

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])