In [1]:
import numpy as np

# 4.2 Universal Functions: Fast Element-Wise Array Functions

#### A universal function, or ufunc, is a function that performs element-wise operations on data in ndarrays.

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr = np.arange(10)

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [7]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

#### Binary uFunc

In [8]:
x = np.random.randn(10)

In [9]:
y = np.random.randn(10)

In [10]:
x

array([-0.81345252,  0.60290157,  0.16875111, -0.786508  ,  1.92686408,
        0.2307329 ,  0.10107711,  0.71769787,  0.66250597,  0.37218014])

In [11]:
y

array([-0.40768964, -0.51393231, -0.67448024,  0.66178725,  0.93155181,
        0.03967163, -0.5389362 ,  0.05781661,  0.04670904, -1.40577592])

In [12]:
np.maximum(x, y)

array([-0.40768964,  0.60290157,  0.16875111,  0.66178725,  1.92686408,
        0.2307329 ,  0.10107711,  0.71769787,  0.66250597,  0.37218014])

In [13]:
reminder, whole_part = np.modf(x)

In [14]:
reminder

array([-0.81345252,  0.60290157,  0.16875111, -0.786508  ,  0.92686408,
        0.2307329 ,  0.10107711,  0.71769787,  0.66250597,  0.37218014])

In [15]:
whole_part

array([-0.,  0.,  0., -0.,  1.,  0.,  0.,  0.,  0.,  0.])

In [16]:
np.abs(x)

array([0.81345252, 0.60290157, 0.16875111, 0.786508  , 1.92686408,
       0.2307329 , 0.10107711, 0.71769787, 0.66250597, 0.37218014])

In [17]:
np.fabs(x)

array([0.81345252, 0.60290157, 0.16875111, 0.786508  , 1.92686408,
       0.2307329 , 0.10107711, 0.71769787, 0.66250597, 0.37218014])

In [18]:
np.square(x)

array([0.661705  , 0.36349031, 0.02847694, 0.61859484, 3.71280516,
       0.05323767, 0.01021658, 0.51509023, 0.43891416, 0.13851806])

In [19]:
x = np.array([1, 2, 3, 4.5, 4, 5.5, 5.6, 5.7, 6, 7.1, 7.23, 7.4567, 7.9, 8, 9, 10.1234])

In [20]:
x

array([ 1.    ,  2.    ,  3.    ,  4.5   ,  4.    ,  5.5   ,  5.6   ,
        5.7   ,  6.    ,  7.1   ,  7.23  ,  7.4567,  7.9   ,  8.    ,
        9.    , 10.1234])

In [21]:
np.square(x)

array([  1.        ,   4.        ,   9.        ,  20.25      ,
        16.        ,  30.25      ,  31.36      ,  32.49      ,
        36.        ,  50.41      ,  52.2729    ,  55.60237489,
        62.41      ,  64.        ,  81.        , 102.48322756])

In [22]:
np.exp(x)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 9.00171313e+01,
       5.45981500e+01, 2.44691932e+02, 2.70426407e+02, 2.98867401e+02,
       4.03428793e+02, 1.21196707e+03, 1.38022250e+03, 1.73142492e+03,
       2.69728233e+03, 2.98095799e+03, 8.10308393e+03, 2.49193528e+04])

In [23]:
np.sign(x)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
np.isfinite(x)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])