# Compare Numpy with List

In [2]:
import numpy as np

In [9]:
my_array = np.arange(1000000)

In [10]:
my_list = list(range(1000000))

In [11]:
%time for _ in range(50): my_array * 2

Wall time: 507 ms


In [12]:
%time for _ in range(50): my_list * 2

Wall time: 6.31 s


# 4.1 The NumPy ndarray: A Multidimensional Array Object

In [3]:
#(rows, columns)
x = np.random.randn(2, 3)

In [4]:
#(rows, columns)
y = np.random.randn(8, 4)

In [21]:
x

array([[-0.01520741, -0.72837525,  0.07076799],
       [ 1.22969933,  0.35499111,  1.75699921]])

In [24]:
y

array([[-0.66651003,  0.75702736, -1.9576011 ,  1.5177726 ],
       [-0.51813929,  0.48214802, -0.69291341, -0.64544476],
       [ 0.90144642,  1.47986954,  1.09900056,  1.37211157],
       [-0.50139148, -0.62882343,  0.73659693, -0.65730852],
       [ 0.2172839 ,  0.28325931,  0.2053734 , -0.79836251],
       [ 0.01639927, -1.66315687,  0.27690046,  1.98745712],
       [ 1.66024351,  0.64330548,  0.29474162, -0.21863125],
       [-0.4483943 , -1.08071825,  1.21844428,  1.18707052]])

In [26]:
x * 10

array([[-0.15207407, -7.28375246,  0.70767989],
       [12.29699333,  3.54991112, 17.56999213]])

In [27]:
y * 10

array([[ -6.66510027,   7.57027356, -19.57601102,  15.17772597],
       [ -5.18139288,   4.8214802 ,  -6.92913406,  -6.45444756],
       [  9.01446419,  14.79869536,  10.99000559,  13.72111568],
       [ -5.01391477,  -6.28823426,   7.36596926,  -6.57308523],
       [  2.17283897,   2.83259307,   2.05373401,  -7.98362505],
       [  0.16399267, -16.63156872,   2.76900457,  19.87457122],
       [ 16.6024351 ,   6.43305483,   2.94741623,  -2.18631251],
       [ -4.48394304, -10.80718255,  12.18444285,  11.87070515]])

In [5]:
x.dtype

dtype('float64')

In [6]:
x.shape

(2, 3)

# Creating ndarray

In [8]:
xarr = np.array([[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]])

In [9]:
xarr.dtype

dtype('int32')

In [10]:
xarr.ndim

2

In [11]:
xarrr = np.array([[[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]]])

In [12]:
xarrr.ndim

3

In [13]:
xarrr

array([[[ 1,  2,  3,  4,  5],
        [11, 22, 33, 44, 55]]])

In [14]:
xarr.shape

(2, 5)

In [15]:
xarrr.shape

(1, 2, 5)

In [29]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.empty((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.zeros((1, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [26]:
np.zeros((2, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [28]:
np.zeros((3, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [33]:
list1 = [1, 2, 3, 4, 5]
np.asarray(list1)

array([1, 2, 3, 4, 5])

In [34]:
list1

[1, 2, 3, 4, 5]

In [35]:
np.array(list1)

array([1, 2, 3, 4, 5])

In [36]:
list1

[1, 2, 3, 4, 5]

In [41]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [49]:
mn = np.ones((2, 3), dtype="float32")
mn

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [48]:
np.ones_like(mn, dtype="int64")

array([[1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [50]:
## alternate zeros() and zeros_like()