In [1]:
import numpy as np

In [6]:
arr3D = np.arange(50).reshape(2, 5, 5)

In [7]:
arr3D

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [8]:
arr3D[1, 2, 3]

38

In [9]:
arr3D[0, 3, 4]

19

In [10]:
arr3D[1,3, :]

array([40, 41, 42, 43, 44])

In [11]:
arr3D[1, 2, 1:3]

array([36, 37])

In [18]:
arr3D[0, 2:, 4:]

array([[14],
       [19],
       [24]])

In [15]:
arr3D[0, 2:, 4]

array([14, 19, 24])

In [16]:
arr3D[0:1, 2:, 4:]

array([[[14],
        [19],
        [24]]])

In [19]:
arr3D[0, 0:, 0]

array([ 0,  5, 10, 15, 20])

In [20]:
arr3D[0:, 0:, 0]

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45]])