In [1]:
import numpy as np

In [5]:
arr3d = np.arange(50).reshape(2,5,5)
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [6]:
arr3d[1,2,3]

38

In [7]:
arr3d[0,3,4]

19

In [8]:
arr3d[1,2:,1:3]

array([[36, 37],
       [41, 42],
       [46, 47]])

In [9]:
arr3d[0,2:,4:]

array([[14],
       [19],
       [24]])

In [12]:
arr3d[0,2:4,4]

array([14, 19])

In [13]:
arr3d[0:1,2:,4:]

array([[[14],
        [19],
        [24]]])

In [14]:
arr3d[0:1,2:,4]

array([[14, 19, 24]])

In [16]:
arr3d[0:,0:,0:1]

array([[[ 0],
        [ 5],
        [10],
        [15],
        [20]],

       [[25],
        [30],
        [35],
        [40],
        [45]]])

# Series

In [17]:
import pandas as pd

In [20]:
obj = pd.Series([10,11,12,13])

In [21]:
obj

0    10
1    11
2    12
3    13
dtype: int64

In [22]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [23]:
obj.values

array([10, 11, 12, 13])

In [24]:
obj1 = pd.Series([13, 25, 56, 85],index = ['a', 'b', 'c', 'd'])
obj1

a    13
b    25
c    56
d    85
dtype: int64

In [25]:
obj1['d']

85

In [28]:
obj1['c']=100

In [29]:
obj1

a     13
b     25
c    100
d     85
dtype: int64

In [70]:
from sklearn.datasets import load_iris
iris=load_iris()
data1=pd.DataFrame(data=np.c_[iris['data'],iris['target']],
                  columns=iris['feature_names']+['target'])

In [71]:
data1.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [32]:
del obj1['c']

In [33]:
obj1

a    13
b    25
d    85
dtype: int64

In [34]:
obj1['z']=1111

In [35]:
obj1

a      13
b      25
d      85
z    1111
dtype: int64

In [38]:
index=[1,2,3,4,5]

In [39]:
obj2 = pd.Series(["apple", "Orange", "Red","Green", "Blue"], index=index)

In [40]:
obj2

1     apple
2    Orange
3       Red
4     Green
5      Blue
dtype: object

In [42]:
obj2[4]

'Green'

In [44]:
obj2[[3,5,1]]

3      Red
5     Blue
1    apple
dtype: object

In [49]:
obj2[obj2=="Orange"]

2    Orange
dtype: object

In [50]:
obj2 *2

1      appleapple
2    OrangeOrange
3          RedRed
4      GreenGreen
5        BlueBlue
dtype: object

In [51]:
print("apple"*5)

appleappleappleappleapple


In [52]:
s1 = pd.Series([100,200,300,400,500],index = ["hun","2h", "3h","4h","5h"])

In [53]:
s1

hun    100
2h     200
3h     300
4h     400
5h     500
dtype: int64

In [54]:
'6h' in s1

False

In [55]:
"4h" in s1

True

In [56]:
##Creating a series using python dictionry

In [57]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [58]:
s2 = pd.Series(sdata)

In [59]:
s2

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [60]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [61]:
s2 = pd.Series(sdata, index=states)

In [62]:
s2

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [63]:
pd.isnull(s2)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [64]:
pd.notnull(s2)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [66]:
s2[pd.isnull(s2)]

California   NaN
dtype: float64

In [67]:
s2[pd.notnull(s2)]

Ohio      35000.0
Oregon    16000.0
Texas     71000.0
dtype: float64

# Data Frames

In [98]:
data1 = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year':  [2000, 2001, 2002, 2001, 2002, 2003],
        'pop':   [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
       }


In [99]:
df = pd.DataFrame(data)

In [100]:
df

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [101]:
data=pd.DataFrame(data, columns=['year', 'state', 'pop'])
data

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [102]:
data = pd.read_csv("banknotes.csv")


In [103]:
data.head()

variace  skewness  curtosis  entropy  class
0  3.62160    8.6661   -2.8073 -0.44699      0
1  4.54590    8.1674   -2.4586 -1.46210      0
2  3.86600   -2.6383    1.9242  0.10645      0
3  3.45660    9.5228   -4.0112 -3.59440      0
4  0.32924   -4.4552    4.5718 -0.98880      0

In [104]:
data.tail(10)

variace  skewness   curtosis  entropy  class
1362 -2.16680   1.59330   0.045122 -1.67800      1
1363 -1.16670  -1.42370   2.924100  0.66119      1
1364 -2.83910  -6.63000  10.484900 -0.42113      1
1365 -4.50460  -5.81260  10.886700 -0.52846      1
1366 -2.41000   3.74330  -0.402150 -1.29530      1
1367  0.40614   1.34920  -1.450100 -0.55949      1
1368 -1.38870  -4.87730   6.477400  0.34179      1
1369 -3.75030 -13.45860  17.593200 -2.77710      1
1370 -3.56370  -8.38270  12.393000 -1.28230      1
1371 -2.54190  -0.65804   2.684200  1.19520      1

In [105]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1372 entries, 0 to 1371
Data columns (total 5 columns):
variace     1372 non-null float64
skewness    1372 non-null float64
curtosis    1372 non-null float64
entropy     1372 non-null float64
class       1372 non-null int64
dtypes: float64(4), int64(1)
memory usage: 53.7 KB


In [106]:
data.describe()

variace     skewness     curtosis      entropy        class
count  1372.000000  1372.000000  1372.000000  1372.000000  1372.000000
mean      0.433735     1.922353     1.397627    -1.191657     0.444606
std       2.842763     5.869047     4.310030     2.101013     0.497103
min      -7.042100   -13.773100    -5.286100    -8.548200     0.000000
25%      -1.773000    -1.708200    -1.574975    -2.413450     0.000000
50%       0.496180     2.319650     0.616630    -0.586650     0.000000
75%       2.821475     6.814625     3.179250     0.394810     1.000000
max       6.824800    12.951600    17.927400     2.449500     1.000000

In [109]:
frame2 = pd.DataFrame(data1, columns=['year', 'state', 'pop', 'debt'],

index=['one', 'two', 'three', 'four','five', 'six'])

In [110]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [141]:
frame2['debt']=[100,200,56,45,78,98]
frame2

year   state  pop  debt
one    2000    Ohio  1.5   100
two    2001    Ohio  1.7   200
three  2002    Ohio  3.6    56
four   2001  Nevada  2.4    45
five   2002  Nevada  2.9    78
six    2003  Nevada  3.2    98

In [142]:
frame2.debt =range(6)

In [143]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

In [120]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [121]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [129]:
frame2[["state", "year"]]

state  year
one      Ohio  2000
two      Ohio  2001
three    Ohio  2002
four   Nevada  2001
five   Nevada  2002
six    Nevada  2003

In [130]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt        2
Name: three, dtype: object

In [132]:
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt        2
Name: three, dtype: object

In [133]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [134]:
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [135]:
frame2['debt'] = val

In [136]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [139]:
frame2.debt[['one',"three",'six']]=[5,10,15]

/home/nasir/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [140]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   5.0
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6  10.0
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2  15.0

In [144]:
frame2['eastern'] = frame2.state == 'Ohio'

In [145]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5     0     True
two    2001    Ohio  1.7     1     True
three  2002    Ohio  3.6     2     True
four   2001  Nevada  2.4     3    False
five   2002  Nevada  2.9     4    False
six    2003  Nevada  3.2     5    False

In [157]:
score = {"python1":[78,67,89,90,99,100,56],
         "python2":[67,87,90,98,56,100,89],
         "AI for EO":[98,78,90,67,76,85,83]}

In [158]:
data = pd.DataFrame(score)

In [159]:
data

python1  python2  AI for EO
0       78       67         98
1       67       87         78
2       89       90         90
3       90       98         67
4       99       56         76
5      100      100         85
6       56       89         83

In [160]:
data["total"]=data.python1+data.python2+data['AI for EO']

In [161]:
data

python1  python2  AI for EO  total
0       78       67         98    243
1       67       87         78    232
2       89       90         90    269
3       90       98         67    255
4       99       56         76    231
5      100      100         85    285
6       56       89         83    228

In [162]:
data['status']=["Pass" if i >=250 else "Fails" for i in data.total]

In [163]:
data

python1  python2  AI for EO  total status
0       78       67         98    243  Fails
1       67       87         78    232  Fails
2       89       90         90    269   Pass
3       90       98         67    255   Pass
4       99       56         76    231  Fails
5      100      100         85    285   Pass
6       56       89         83    228  Fails