In [1]:
import numpy as np

In [3]:
## range in numpy
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [6]:
##multidimentional Array in numpy
np.random.rand(3,4)

array([[0.54551307, 0.30678906, 0.50714408, 0.16417725],
       [0.02469285, 0.62252031, 0.37709683, 0.35252916],
       [0.717175  , 0.82277816, 0.62900482, 0.24766922]])

In [7]:
## easiest way to create array
list1 = [1, 2, 3, 4, 5, 6, 7]
data = np.array(list1)

In [8]:
data

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
data.shape

(7,)

In [11]:
data.dtype

dtype('int32')

In [23]:
data.ndim

1

In [18]:
## Two dimension array
list2 = [ [1, 2, 3, 4, 5], [11, 12, 13, 14, 15] ]
data2 = np.array(list2)

In [19]:
data2

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [20]:
data2.dtype

dtype('int32')

In [21]:
data2.shape

(2, 5)

In [24]:
data2.ndim

2

In [26]:
## two dimension array with not equal in length
list3 = [ [1, 2, 3], [11, 12, 13, 14] ]
data3 = np.array(list3)

In [27]:
data3

array([list([1, 2, 3]), list([11, 12, 13, 14])], dtype=object)

In [28]:
data3.dtype

dtype('O')

In [29]:
data3.ndim

1

In [30]:
## still two dimensional array
list4 = [ [1, 2, 3], [11, 12, 13], [21, 22, 23] ]
data4 = np.array(list4)

In [31]:
data4

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23]])

In [32]:
data4.ndim

2

In [33]:
## three dimensional array
list5 = [ [ [1, 2, 3], [6, 7, 8] ], [ [12, 13, 14 ], [16, 17, 18 ] ] ]
data5 = np.array(list5)
data5

array([[[ 1,  2,  3],
        [ 6,  7,  8]],

       [[12, 13, 14],
        [16, 17, 18]]])

In [34]:
data5.ndim

3

In [35]:
## four dimensional array
list6 = [ [ [ [1.0, 2.0, 3.0 ], [1.1, 1.2, 1.3 ] ], [ [0.001, 0.002, 0.003 ], [0.006, 0.007, 0.008 ] ] ], [ [ [12.000, 13.000, 14.000], [12.000, 13.000, 14.000 ] ], [ [16.999, 17.999, 18.999], [16.999, 17.999, 18.999] ] ] ]
data6 = np.array(list6)
data6

array([[[[1.0000e+00, 2.0000e+00, 3.0000e+00],
         [1.1000e+00, 1.2000e+00, 1.3000e+00]],

        [[1.0000e-03, 2.0000e-03, 3.0000e-03],
         [6.0000e-03, 7.0000e-03, 8.0000e-03]]],


       [[[1.2000e+01, 1.3000e+01, 1.4000e+01],
         [1.2000e+01, 1.3000e+01, 1.4000e+01]],

        [[1.6999e+01, 1.7999e+01, 1.8999e+01],
         [1.6999e+01, 1.7999e+01, 1.8999e+01]]]])

In [36]:
data6.ndim

4

In [37]:
data6.dtype

dtype('float64')

In [41]:
listOne = [1, 2, 3, 4]
listTwo = [ [1, 2, 3], [11, 12, 13] ]
listThree = [ [ [ 1, 2, 3], [ 11, 12, 13 ] ] ]
listFour = [ [ [ [ 1, 2, 3 ], [ 11, 12, 13 ] ] ] ]
dataOne = np.array(listOne)
dataTwo = np.array(listTwo)
dataThree = np.array(listThree)
dataFour = np.array(listFour)

In [42]:
print("One Dimensional Array ")
print(dataOne)
print(dataOne.ndim)
print("Two Dimensional Array ")
print(dataTwo)
print(dataTwo.ndim)
print("Three Dimensional Array ")
print(dataThree)
print(dataThree.ndim)
print("Four Dimensional Array ")
print(dataFour)
print(dataFour.ndim)

One Dimensional Array 
[1 2 3 4]
1
Two Dimensional Array 
[[ 1  2  3]
 [11 12 13]]
2
Three Dimensional Array 
[[[ 1  2  3]
  [11 12 13]]]
3
Four Dimensional Array 
[[[[ 1  2  3]
   [11 12 13]]]]
4


# Creating Array and Genrating Values

In [4]:
#it works on only scaler arguments
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#it takes scaler as well as vector
print(np.zeros(10))
print("------------------")
print(np.zeros((2, 3)))
print("------------------")
print(np.zeros((2, 3, 4)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
------------------
[[0. 0. 0.]
 [0. 0. 0.]]
------------------
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [9]:
#it takes scaler as well as vector
print(np.empty(10))
print("------------------")
print(np.empty((2, 3)))
print("------------------")
print(np.empty((2, 3, 4)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
------------------
[[0. 0. 0.]
 [0. 0. 0.]]
------------------
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [3]:
#it takes scaler as well as vector
print(np.ones(10))
print("------------------")
print(np.ones((2, 3)))
print("------------------")
print(np.ones((3, 2, 4)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
------------------
[[1. 1. 1.]
 [1. 1. 1.]]
------------------
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [4]:
np.ones((3, 2, 4)).ndim

3

In [12]:
c = np.full((4,3), fill_value='6', dtype='int32')
c

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [8]:
d = np.full_like(c, fill_value='10')
d

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [17]:
print(np.eye(4,4))
print("---------------------")
print(np.identity(8))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
---------------------
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [15]:
onD = np.ones(10)
onD1 = np.ones((2, 1))
onD2 = np.ones((3, 1,  2))
onD3 = np.ones((4, 2,  2, 3))
onD4 = np.ones((4, 1, 2, 3, 5))
print(onD)
print(onD.ndim) 
print("-------------")
print(onD1) 
print(onD1.ndim) 
print("-------------")
print(onD2) 
print(onD2.ndim) 
print("-------------")
print(onD3) 
print(onD3.ndim) 
print("-------------")
print(onD4) 
print(onD4.ndim) 
print("-------------")

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
1
-------------
[[1.]
 [1.]]
2
-------------
[[[1. 1.]]

 [[1. 1.]]

 [[1. 1.]]]
3
-------------
[[[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]]
4
-------------
[[[[[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]]]



 [[[[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]]]



 [[[[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]]]



 [[[[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]]]]
5
-------------


In [13]:
dd = np.ones((1, 2, 3, 4, 3, 2))
print(dd.ndim)
dd

6


array([[[[[[1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.],
           [1., 1.]]],


         [[[1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.],
           [1., 1.]]],


         [[[1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.],
           [1., 1.]]]],



        [[[[1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1

# Arithmetic with NumPy Arrays

In [20]:
row1 = [1, 2]
row2 = [3, 4]
z = np.array((row1, row2))

In [21]:
z

array([[1, 2],
       [3, 4]])

In [22]:
row11 = [11, 12]
row22 = [8, 9]
y = np.array((row11, row22))

In [23]:
y

array([[11, 12],
       [ 8,  9]])

In [34]:
print("-------Addition--------")
print(f" {z} \n + \n {y}\n = \n{z + y}")
print("-------Subtraction--------")
print(f" {z} \n - \n {y}\n = \n{z - y}")
print("-------Multiplication--------")
print(f" {z} \n * \n {y}\n = \n{z * y}")
print("-------Division--------")
print(f" {z} \n / \n {y}\n = \n{z / y}")
print("-------Greater--------")
print(f" {z} \n > \n {y}\n = \n{z > y}")
print("-------Lesser--------")
print(f" {z} \n < \n {y}\n = \n{z < y}")

-------Addition--------
 [[1 2]
 [3 4]] 
 + 
 [[11 12]
 [ 8  9]]
 = 
[[12 14]
 [11 13]]
-------Subtraction--------
 [[1 2]
 [3 4]] 
 - 
 [[11 12]
 [ 8  9]]
 = 
[[-10 -10]
 [ -5  -5]]
-------Multiplication--------
 [[1 2]
 [3 4]] 
 * 
 [[11 12]
 [ 8  9]]
 = 
[[11 24]
 [24 36]]
-------Division--------
 [[1 2]
 [3 4]] 
 / 
 [[11 12]
 [ 8  9]]
 = 
[[0.09090909 0.16666667]
 [0.375      0.44444444]]
-------Greater--------
 [[1 2]
 [3 4]] 
 > 
 [[11 12]
 [ 8  9]]
 = 
[[False False]
 [False False]]
-------Lesser--------
 [[1 2]
 [3 4]] 
 < 
 [[11 12]
 [ 8  9]]
 = 
[[ True  True]
 [ True  True]]


# Basic Indexing and Slicing

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
arr[6:9] = 120
arr

array([  1,   2,   3,   4,   5,   6, 120, 120, 120,  10,  11,  12,  13,
        14,  15])

In [6]:
arr_slice = arr[6:9]
arr_slice

array([120, 120, 120])

In [7]:
arr_slice[1] = 90
arr_slice

array([120,  90, 120])

In [8]:
arr

array([  1,   2,   3,   4,   5,   6, 120,  90, 120,  10,  11,  12,  13,
        14,  15])

In [9]:
arr_slice_copy = arr[11:14].copy()
arr_slice_copy

array([12, 13, 14])

In [10]:
arr_slice_copy[1] = 10000
arr_slice_copy

array([   12, 10000,    14])

In [11]:
arr

array([  1,   2,   3,   4,   5,   6, 120,  90, 120,  10,  11,  12,  13,
        14,  15])

In [12]:
arr2D = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
arr2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr2D[1][2]

6

In [15]:
arr2D[0]

array([1, 2, 3])

In [16]:
arr2D[[0, 1]]

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
#to catch 6 and 9
arr2D[[1, 2], [2]]

array([6, 9])

In [21]:
# 3D Array
arr3D = np.array( [ [ [11, 12, 13], [14, 15, 16] ], [ [21, 22, 23], [24, 25, 26] ] ] )
arr3D

array([[[11, 12, 13],
        [14, 15, 16]],

       [[21, 22, 23],
        [24, 25, 26]]])

In [22]:
#to select 15, 16, 22 and 23
arr3D[0]

array([[11, 12, 13],
       [14, 15, 16]])

In [23]:
arr3D[0, 1]

array([14, 15, 16])

In [53]:
arr3D[ [0,1], [1,0] ] [ [0,1], 1:3 ]
#Mission acomplish

array([[15, 16],
       [22, 23]])

# Boolean Indexing

In [62]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 3)

In [63]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [64]:
data

array([[ 0.81844844, -1.72162507,  0.8840978 ],
       [ 0.83086103, -0.76306529, -0.38753516],
       [-1.55508104,  0.45516345, -0.34828369],
       [ 0.21814079,  0.34515678, -0.54736457],
       [-1.84093663,  0.06792371, -1.76350105],
       [ 0.28809798, -2.03359643,  0.76383723],
       [-1.49458392,  0.36317937,  0.46555951]])

In [65]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [68]:
data[names == 'Bob']

array([[ 0.81844844, -1.72162507,  0.8840978 ],
       [ 0.21814079,  0.34515678, -0.54736457]])

# Fancy Indexing

In [2]:
arrF = np.empty((8, 4))

In [3]:
for i in range(8):
    arrF[i] = i

In [4]:
arrF

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [7]:
arrF[[1, 3, 5, 7], 1:]

array([[1., 1., 1.],
       [3., 3., 3.],
       [5., 5., 5.],
       [7., 7., 7.]])

In [8]:
arrFF = np.arange(24).reshape((6, 4))
arrFF

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [9]:
arrFF.T

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])